version: '3.7'
services:
  app1:
    image: app1:latest
    build: ./app1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  app2:
    image: app2:latest
    build: ./app2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  db:
    image: mysql:8.0.21
    secrets:
      root_password:
        external: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - target: 3306
      published: 3306
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/root_password
      MYSQL_DATABASE: "db"
